package org.kuraterut.verartitgbotformaster.utils;

public enum BotState {
    START,
    AWAITING_AUTHORIZATION_PHONE,
    AWAITING_AUTHORIZATION_PASSWORD,
    MAIN_MENU,
    AWAITING_SCHEDULE_DATE,
    PROFILE_MENU,
    AWAITING_PROFILE_NEW_FIO,
    AWAITING_PROFILE_NEW_BIO
}
